server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.38.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.38.130
